// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Get from "../../../platform/utilities/data/get";

function isNotAnonymous(formData) {
  return formData.onBehalfOf !== "Anonymous";
}

function isMyself(formData) {
  return formData.onBehalfOf === "Myself";
}

function isNotMyself(formData) {
  if (formData.onBehalfOf === "Someone else") {
    return true;
  } else {
    return formData.onBehalfOf === "Anonymous";
  }
}

function isVeteranOrServiceMember(formData) {
  if (isNotMyself(formData)) {
    return false;
  } else {
    return !List.exists((function (x) {
                  return x === formData.serviceAffiliation;
                }), /* :: */[
                "Spouse",
                /* :: */[
                  "Child",
                  /* :: */[
                    "Other",
                    /* [] */0
                  ]
                ]
              ]);
  }
}

function manualSchoolEntryIsChecked(formData) {
  return Get.default("educationDetails.school.view:searchSchoolSelect.view:manualSchoolEntryChecked", formData);
}

function isUS(formData) {
  return Get.default("educationDetails.school.view:manualSchoolEntry.address.country", formData) === "United States";
}

function manualSchoolEntryIsNotChecked(formData) {
  return !Get.default("educationDetails.school.view:searchSchoolSelect.view:manualSchoolEntryChecked", formData);
}

function manualSchoolEntryIsCheckedAndIsUS(formData) {
  if (Get.default("educationDetails.school.view:searchSchoolSelect.view:manualSchoolEntryChecked", formData)) {
    return isUS(formData);
  } else {
    return false;
  }
}

var relationships = /* record */[
  /* myself */"Myself",
  /* someoneElse */"Someone else",
  /* anonymous */"Anonymous"
];

var myself = "Myself";

var someoneElse = "Someone else";

var anonymous = "Anonymous";

export {
  relationships ,
  myself ,
  someoneElse ,
  anonymous ,
  isNotAnonymous ,
  isMyself ,
  isNotMyself ,
  isVeteranOrServiceMember ,
  manualSchoolEntryIsChecked ,
  isUS ,
  manualSchoolEntryIsNotChecked ,
  manualSchoolEntryIsCheckedAndIsUS ,
  
}
/* ../../../platform/utilities/data/get Not a pure module */
